version: '2'
services:
  spingularchatsql-app:
    image: spingularchatsql
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:postgresql://spingularchatsql-postgresql:5432/spingularchatsql
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  spingularchatsql-postgresql:
    extends:
      file: postgresql.yml
      service: spingularchatsql-postgresql
