version: '2'
services:
  spingularchatsql-postgresql:
    image: postgres:11.2
    # volumes:
    #     - ~/volumes/jhipster/spingularchatsql/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=spingularchatsql
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
